### ISSUE TITLE
Return elements based on an XPath query

### ISSUE THREAD

**Issue by ankur-sharda** [browserless/chrome#1118]
It would be great to be able to get elements based on an XPath query.

In my case I use XPath to only return elements that have some text or other content within them. Simply selecting on tag names will return a lot of unnecessary and extra results.

I guess the curl might look something like this:

curl -X POST \
  https://chrome.browserless.io/scrape?token=MY_API_TOKEN \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "url": "https://example.com/",
  "xpath": "** some xpath query here **"
  }]
}'

And the results would have the same format as is currently the case.

**Comment by joelgriffith** [comment]
Hey, thanks for the suggestion! Looking at our source for scrape, and the XPath specification, I'm afraid it's not a good match. X-Path has a lot of power by itself, and getting all the proper parsing and iterating in the scrape API isn't something that can be done easily for now.

I'd recommend using something like the `/function` endpoint to parse and get results manually, since it'll allow you full control over results and how to parse them
