### ISSUE TITLE
Incapsula blocking on browserless Chrome but not not on local computer

### ISSUE THREAD

**Issue by OwaisSiddiqui** [browserless/chrome#1225]
**Describe the bug**
I have a browserless dedicated plan for its cloud hosting services. I have a script which scrapes a website. The website I scrape has Incapsula (now Imperva, https://www.imperva.com, a bot blocking service for websites). When I run the script without the browserless API token (without `puppeteer.connect` and on my local computer), it runs fine i.e. I don't get Incapsula bot blocking pages (I use `headless: false`). However, when I use it with browserless (with `puppeteer.connect` with `&headless=false`), every page of the website I scrape gets hit by Incapsula's bot blocking page. I am not sure how I can debug this or how to get around this.

**To Reproduce**
Scrape a Incapsula protected website with browserless Chrome.

**Expected behavior**
To not hit the Incapsula bot blocking pages like on my local computer.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur (11.1)
 - Browser: Chrome
 - Version: Puppeteer Version

**Comment by joelgriffith** [comment]
I can't fix how they do bot detection or scraping detection as it could be IP detection, some kind of bot detection, or literally anything else. I'd recommend trying the stealth option here: https://github.com/browserless/chrome/pull/1088, otherwise you might need a proxy service to help mask what you're attempting to do.
