### ISSUE TITLE
How many concurrent headless Chrome browsers can I run on X vCPUs and X gb of ram?

### ISSUE THREAD

**Issue by OwaisSiddiqui** [browserless/chrome#1399]
**Describe the bug**
This is not a bug nor a feature request so I wasn't sure how to categorize this type of question. I am wondering how many concurrent headless Chrome Puppeteer browsers can I run on X vCPUs and X gb of ram such that it does not crash the docker container or slow down the browsers too much. Currently, I have a AWS ECS (Elastic Container Service) running the browserless docker container. I have set the maximum concurrent browsers to be 20 and maximum queue length to be 20 as well. The container has 2 vCPUs and 4gb ram. Right now, there is no issue with a slow browsers but I was hoping to know the maximum amount of concurrent browsers I can run such that it does not slow down too much. If I do want more, I know I would need more ram but will I need more vCPUs or are 2 enough?

**Comment by joelgriffith** [comment]
We generally recommend 1GB/1CPU per concurrent request if you're scraping the internet. Otherwise, you can get more performance by consuming really simple static sites (IE no JS or lots of network calls). Potentially up to 10 concurrent per GB/CPU. Largely depends on the type of work you're doing as well.
