### ISSUE TITLE
Difference between chrome-stable and puppeteer-x

### ISSUE THREAD

**Issue by howiezhao** [browserless/chrome#1709]
Hello i am confused with a question:

What is the difference between the `chrome-stable` and `puppeteer-x` tags in the docker image? Which image should I pull?

Sorry, I did not find an explanation for this in the documentation. Do I need to supplement the relevant documentation?

**Comment by joelgriffith** [comment]
Hey there, good question, we should probably have this someplace documented.

The chrome stable tags are chrome proper (not chromium), whereas the puppeteer tags are chromium versions that correspond to that specific version of puppeteer.

In general it’s best to use the puppeteer tags as they’re advertised to work “guaranteed.” Otherwise we’ve noticed that chrome itself is a bit more stable overall (from the context of our CI), but comes with the caveat that it might not work 100% of the time with what puppeteer expects, though we’ve never really noticed that.
