### ISSUE TITLE
Latest docker image version cannot find user blessuser on deploy

### ISSUE THREAD

**Issue by AlexAVL** [browserless/chrome#1901]
**Describe the bug**
The image does not deploy and throws an error:

```
Cannot start service browserless: unable to find user blessuser: no matching entries in passwd file
```

**To Reproduce**
Deploy from dockerhub

**Expected behavior**
The image is deployed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10

**Comment by AlexLoyola** [comment]
Hey Alex!
We weren’t able to reproduce this issue with the details provided, unfortunately.
Could you provide more information on how/where you’re deploying this?
If you could share steps/commands that you used that lead you to this error, it would be great!

**Comment by joelgriffith** [comment]
Going to close this due to inactivity -- I'm unable to verify this locally, and I'm guessing it's with how things are deployed in their environment.

If that's not the case please open a new issue and let us know _exactly_ how you're running:

- Your docker params for running
- The hosting provider (if any)
