### ISSUE TITLE
Using browserless within a REST API server

### ISSUE THREAD

**Issue by kimyx** [browserless/chrome#2161]
**Is your feature request related to a problem? Please describe.**
We want to use browserless to scrape pages and return the results within REST API calls handled by our server. (We're currently doing this directly with playwright java, not using browserless.) We want to keep the session alive to avoid having to log in again to the same site, navigate to a search page, and enter search criteria. It's frequently the case that our user wants to refresh the same search. But the call to our REST API returns and the playwright objects are closed or abandoned, so we have to start over on the next call. With playwright java, the disconnect function isn't available and, even if it was, the pages are lost on disconnect.

**Describe the solution you'd like**
A way to keep the browserless playwright websocket alive after the browser object is abandoned when our API handler method exits, then reconnect to the same session when we handle the next REST API call.

**Describe alternatives you've considered**
Don't close the java browser object when exiting our API handler. Instead put the still-open java browser object in a pool that survives for a specified time (after which it is closed). Connect on next entry by finding the previous wsEndpoint. But I'm not sure if that wastes java resources and closing the pooled browser kills the current one.

**Additional context**
We provide a front end and API allowing users to search for and bid on commodities across numerous providers. The commodities appear and are consumed rapidly, so users need to refresh their view often. Some providers offer their own API, but others have just websites, and that's where the scraping comes in. Performance of the scraping is critical.

**Comment by andyMrtnzP** [comment]
Sadly, there's no way to "disconnect" from a browser, with Playwright, the browser context is "owned" by the connected client. When the client closes the connection — or is interrupted —, its contexts will be closed automatically. This is an issue that has been talked about before https://github.com/microsoft/playwright/issues/4956#issuecomment-758931019. 

One workaround would be to create a `connection.jar` that only connects to Browserless and keeps running — with the [keepalive query string](https://www.browserless.io/docs/chrome-flags#keeping-the-browser-alive) — and have Playwright connect to that specific instance (you can see you instances in the `/session` API). You could take a look to [this calebeby's repo](https://github.com/calebeby/playwright-test) (uses NodeJS). This approach has the same problem of not disconnecting without closing the instance, so you would have to be extremely cautious about your connections and not letting zombie processes open. 

There's also the Java part, which adds a complexity layer due to the async nature of the remote connection.

**Comment by kimyx** [comment]
Thanks for the comments, Andy. We abandoned playwright and switched to a lower level but more efficient approach that emulates the various http calls made within each website, with token/cookie caching as needed. We considered something like your connection.jar but it didn't seem to gain enough advantage to be worthwhile.

**Comment by jlia0** [comment]
> Sadly, there's no way to "disconnect" from a browser, with Playwright, the browser context is "owned" by the connected client. When the client closes the connection — or is interrupted —, its contexts will be closed automatically. This is an issue that has been talked about before [microsoft/playwright#4956 (comment)](https://github.com/microsoft/playwright/issues/4956#issuecomment-758931019).
> 
> One workaround would be to create a `connection.jar` that only connects to Browserless and keeps running — with the [keepalive query string](https://www.browserless.io/docs/chrome-flags#keeping-the-browser-alive) — and have Playwright connect to that specific instance (you can see you instances in the `/session` API). You could take a look to [this calebeby's repo](https://github.com/calebeby/playwright-test) (uses NodeJS). This approach has the same problem of not disconnecting without closing the instance, so you would have to be extremely cautious about your connections and not letting zombie processes open.
> 
> There's also the Java part, which adds a complexity layer due to the async nature of the remote connection.

Do you mind sharing more about the workaround? What is `connections.jar`?
