### ISSUE TITLE
Opt redis for queues 

### ISSUE THREAD

**Issue by j-mendez** [browserless/chrome#2343]
**Is your feature request related to a problem? Please describe.**

Ability to scale queues with redis instead of internal memory.

**Describe the solution you'd like**
 
Add optional redis client usage for queues to scale via dedicated.

**Comment by joelgriffith** [comment]
Is there more specifics you're looking for? Right now we use internal memory for "queueing" because we don't run users code ourselves, so queueing has to be at the time of the HTTP request (hence why it's done in memory rather than trying to do a proper queue).

Can you describe in more detail (perhaps with links to source) on where/how you envision redis interacting with browserless? I might be misunderstanding since our queue is simply just a mechanism to "hold" onto HTTP/Websocket connections without running them immediately

**Comment by j-mendez** [comment]
Hi @joelgriffith , thank you for the detailed explanation and work for the project. I envisioned using this on a AWS Fargate task that is limited with memory. I was thinking exactly that for the connection holding aspect when used in parallel with around 1,000 request coming in continuously if the queue can be shared throughout the task via message brokers or redis etc so it can be used in a clustered manner to scale.
