### ISSUE TITLE
Browserless docker throws error with selenium4

### ISSUE THREAD

**Issue by praveendvd** [browserless/chrome#2389]
**Describe the bug**

Selenium is not able to connect to browserless

**To Reproduce**

**Start docker as `:**

```
docker pull browserless/chrome:1-arm64
docker run -p 3000:3000 browserless/chrome
```

**Then run selenium code as :**

```
const {Builder, Browser, By, Key, until, Capabilities} = require('selenium-webdriver');

(async function example() {
    const chromeCapabilities = Capabilities.chrome();
    chromeCapabilities.set(
      'chromeOptions', {
        args: [
          '--headless',
          '--no-sandbox',
        ],
      }
    );
    

  let driver = new Builder()
  .forBrowser('chrome')
  .withCapabilities(chromeCapabilities)
  .usingServer('http://localhost:3000/webdriver') // <-- Apply usingServer and that's it
  .build();
  
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();
```

**Reproducible project :**

[untitled folder.zip](https://github.com/browserless/chrome/files/8750029/untitled.folder.zip)

**Expected behavior**

SHould be able to connect as expected 

**Screenshots**

<img width="821" alt="image" src="https://user-images.githubusercontent.com/45095911/169666295-4352a37a-322d-45b2-8461-bcc7fb9e3ee8.png">

**Desktop (please complete the following information):**
 <img width="406" alt="image" src="https://user-images.githubusercontent.com/45095911/169666315-ca9c1243-4d18-404c-ac6c-8137ac99b7e2.png">
**Additional context**

Logs :

[mylogs.txt](https://github.com/browserless/chrome/files/8748249/mylogs.txt)

**Comment by joelgriffith** [comment]
Unfortunately this is related to https://github.com/browserless/chrome/issues/2004. Sadly, this is to say, that M1 mac's can't run this docker image just yet. It's a longer story as to why that is (mostly that Google doesn't build ARM compatible chromedriver binaries for Ubuntu), and the images out there that _do_ have chromedriver support for m1 are using a quite-old version of chromium that will likely break at some point.

Closing due to this being a duplicate, but likely won't be able to fix in the near future.
