### ISSUE TITLE
Can't open the new page

### ISSUE THREAD

**Issue by yuzhen45** [browserless/chrome#2612]
**Describe the bug**
robotframework-browser base on playwright
We can still use it normally on August 11th，but after the August 12th update, the new page cannot be opened.

**To Reproduce**
robotframework==5.0.1
robotframework-browser==13.4.0
browserless==lastest(2022/8/12-Linux amd64)
browser==chrome
code
```
*** Settings ***
Library    Browser

*** Test Cases ***
Debug open page
    Connect To Browser    wsEndpoint=ws://localhost:3000/playwright
    New Page    https://www.baidu.com/
    Take Screenshot
```
**Error Screenshots**
![image](https://user-images.githubusercontent.com/111275548/184608042-f925df65-2539-4331-9394-b00b004be17a.png)

**Expected behavior**
can open the new page

**Comment by joelgriffith** [comment]
This is unfortunately due to a playwright version mismatch. Please check the version of playwright we have installed and match it to your version running locally. We're working on fixing this in the future, but for the time being the best workflow is to match your playwright version with what browserless has installed since they're tightly coupled.
