### ISSUE TITLE
Push image to a different registry, in addition to Docker Hub

### ISSUE THREAD

**Issue by onedr0p** [browserless/chrome#2970]
Is your feature request related to a problem? Please describe.

Hi 👋🏼  In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

Describe the solution you'd like

Push your images to an additional registry like Quay or GHCR

Thanks!

**Comment by gabe565** [comment]
Quick update for this issue: Yesterday, Docker announced that they will be removing open source organizations within the next month, as detailed in [this unnoficial blog post](https://blog.alexellis.io/docker-is-deleting-open-source-images/).

Since then, Docker has apologized for the miscommunication in [this official blog post](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), but regardless of whether browserless is affected, DockerHub may not be a safe provider of Docker images anymore.

I'd love to see a mirror of the current images in GHCR!

**Comment by joelgriffith** [comment]
We're working on a mirror -- stay tuned. This is something we've wanted to "own" ourselves for a while now but takes time to get parts of it right.

**Comment by joelgriffith** [comment]
V2 is now on ghcr.io, closing
