### ISSUE TITLE
May not be possible to run Dockerfile on Google Cloud Run

### ISSUE THREAD

**Issue by danoc** [browserless/chrome#331]
Hi! Thanks for this great resource.

I'm trying to run the Dockerfile on Google Cloud Run. One of the [requirements of Cloud Run](https://cloud.google.com/run/docs/developing#code_requirements) is:

> The service must listen for requests on the port defined by the PORT environment variable.

The Browserless site suggests using `docker run -p 8080:3000`, but Cloud Run doesn't provide a way to do this kind of port mapping.

Is there another way to do this? Or would this require a change to Browserless?

Thanks!

**Comment by knksmith57** [comment]
The batteries-included `browserless/chrome` image actually does respect `$PORT`; however, because the container is configured to run as a non-privileged user, only ports > 1024 are going to bind successfully.

Unfortunately, Cloud Run doesn't make any guarantees about the port range it'll request, and, after trying myself, I can confirm that Cloud Run can set `$PORT` < 1024.

Given you're likely already re-tagging + publishing the browserless image to your own GCR registry, there's a quick fix: extend the `browserless/chrome` image you're currently targeting and [change the user](https://docs.docker.com/engine/reference/builder/#user) to one with privileges to bind to all ports (eg: back to `root`):

```Dockerfile
FROM browserless/chrome:1-chrome-stable
USER root
```

**Comment by joelgriffith** [comment]
Pretty much what @knksmith57 said: you'll likely need to run as a privileged user if the port assignments are less than 1024. Otherwise it'd be nice if they could specify a range?

**Comment by joelgriffith** [comment]
https://github.com/browserless/chrome/blob/master/src/config.ts#L120

**Comment by danoc** [comment]
Thanks, @joelgriffith and @knksmith57! I'll try this out tonight and report back. I'll share my Dockerfile if it works well. 😄

**Comment by joelgriffith** [comment]
Looks like websockets aren't really supported on Cloud Run `https://github.com/ahmetb/cloud-run-faq#are-websockets-supported-on-cloud-run`

**Comment by danoc** [comment]
Ah, right! 

They list the lack of support as a ["Known Issue"](https://cloud.google.com/run/docs/issues) which, I imagine, means that they plan to add support in the future.

I'll close this for now and then circle back once they have support for it! Thanks again for digging into this.

**Comment by joelgriffith** [comment]
Yup, no worries. I did a test and their service took roughly 2-3 seconds to screenshot example.com with Chrome pre-started. Our usage-based cluster does it in roughly 600ms, and wo Chrome pre-started.

I know others have complained about slow start times in GCP, so use caution if speed is necessary.

**Comment by danoc** [comment]
> I know others have complained about slow start times in GCP, so use caution if speed is necessary.

Yeah, the [Chrome built into Cloud Functions is sadly very slow](https://github.com/GoogleChrome/puppeteer/issues/3120).
