### ISSUE TITLE
AWS Load Balancers and browserless

### ISSUE THREAD

**Issue by michaldul** [browserless/chrome#425]
Can AWS Application Load Balancer or Network Load Balancer be used with browserless containers? Do options like nginx's `worker_connections` required to limit number browserless active WS sessions (established via CDP)?

I'm evaluating whether browserless fits the existing environment. Unfortunately, nginx is no go in this case.

**Comment by joelgriffith** [comment]
Hey! Sorry for the delay! I think either should work, however since we use WebSockets a fair bit, you'll need something that can understand and load raw TCP connections as well (which I think the Network Load Balancer would do?). `worker_connections` are purely a nginx thing, and don't need to be set to anything specific, so I wouldn't worry about that.

Anything that can load-balance raw TCP, or that specifies WS as a supported feature, should work just fine.
