### ISSUE TITLE
How to disable debugger ?

### ISSUE THREAD

**Issue by previa** [browserless/chrome#559]
Some sites contain the following code  blocking evaluation from puppeteer. 

`(function () {var a = new Date(); debugger ; return new Date() -a >100;} )`

Is there anyway to disable debugger or not open debugger by default ? Thanks.

**Comment by joelgriffith** [comment]
Is this on our debugger app, or just doing normal puppeteer stuff?

**Comment by previa** [comment]
Those code would block execution from puppeteer if chrome open with inspect panel. So I am wondering if browserless allow user to disable debug  panel.

**Comment by joelgriffith** [comment]
You can definitely do this with puppeteer, though you'll have to [create a client](https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-targetcreatecdpsession) and use the debugger domain to disable this: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-disable.

Since this isn't directly related to browserless, but is something that can be done with the above, I'm going to close this issue. Please re-open if I'm incorrect or missing something!

**Comment by previa** [comment]
Your reference helps me a lot. Thank you.
