### ISSUE TITLE
screencast in node app with puppeteer

### ISSUE THREAD

**Issue by assiomatica** [browserless/chrome#748]
I am tring to use screencast in this way within a node express application:

app.get('/r', async(req, res) => {
    let browser = null;
    try {
        browser = await puppeteer.connect({ browserWSEndpoint: 'ws://3.126.198.20:8080' });
        const page = await browser.newPage();

        await page.goto('http://www.example.com/');

        await page.waitFor(5000);
        startScreencast();
        await page.waitFor(20000);
        stopScreencast();

        res.send('ok');

        // res.end(screenshot, 'binary');
    } catch (error) {
        if (!res.headersSent) {
            res.status(400).send(error.message);
        }
    } finally {
        if (browser) {
            browser.close();
        }
    }

});

it works (any error) but how to get or save the recorded video?

it's possible to start and stop the recording with an api?

Thanks

**Comment by joelgriffith** [comment]
Your code ` await puppeteer.connect({ browserWSEndpoint: 'ws://3.126.198.20:8080' });` is connection via puppeteer. The screencast API is meant to be ran over an HTTP REST connection: https://docs.browserless.io/docs/screencast.html (you'll notice we do a POST call over HTTP, and not a puppeteer.connect call).

Unfortunately there's no way to do this only with just puppeteer. Your code, as it stands, won't fundamentally work since `startScreencast` and `stopScreencast` are not defined.
