### ISSUE TITLE
Exception with latest Docker-Image

### ISSUE THREAD

**Issue by blafa** [browserless/chrome#755]
With the latest Docker-Image we get an Exception when Connect to browserless

![image](https://user-images.githubusercontent.com/36913028/82338425-2c6f1e00-99ed-11ea-8cdc-9a3f45e4f914.png)

any ideas?

**Comment by joelgriffith** [comment]
Session closed generally means lack of resources to keep the page open (unless there's a race-condition in your call to close the browser).

Generally, when I see these, the solution is to add more resources to the machine running the image. Otherwise, we run latest on our demo box, and it seems to be doing well, so I don't think there's something wrong with the image. I'd try adding more resources and seeing if the problem goes away!

**Comment by a10kiloham** [comment]
I had this issue too but downgrading worked fine to the version from a couple weeks ago. Somethings weird

**Comment by blafa** [comment]
@a10kiloham yes downgrade works. We don't have issues with version chrome:1.33.1-chrome-stable. but latest version keeps crashing with the same ressource-configurations

**Comment by a10kiloham** [comment]
thanks glad it's not just me. i can't provide much debugging help but it def crashes a ton unless I use 1.33 stable!
