### ISSUE TITLE
How to loop on /scrape api

### ISSUE THREAD

**Issue by vinodhum** [browserless/chrome#835]
Hi,
I am using browserless docker image, using /scrape api, I am able scrape single page fine but how to loop through next page and scrape same element again.
currently it just scrape one page only.
is it possible to loop through next page click and scrape same element.

**Comment by joelgriffith** [comment]
/scrape (and other APIs) are only meant to operate on per-page basis, since it can be non-deterministic if there are multiple pages needing some kind of automation.

I'd recommend using something like our function api: https://docs.browserless.io/docs/function.html to do your multi-page execution, since it give you total control over the browser/pages being used.
