### ISSUE TITLE
Support for puppeteer-extra

### ISSUE THREAD

**Issue by kevin-lindsay-1** [browserless/chrome#838]
I'm trying to see if there's a set of functionality offered similar to `puppeteer-extra-plugin-stealth` and other plugins for `puppeteer-extra`, but as far as I'm aware, this package is currently incompatible with plugins.

Would be nice if such functionality could be supported, and if it's already possible, that use case in the documentation would be very helpful.

**Comment by joelgriffith** [comment]
puppeteer-extra does have a connect method, so you can use it on the client end (in your code). Functions and other APIs don’t currently support it just yet

**Comment by kevin-lindsay-1** [comment]
Correct me if I'm wrong, but don't I have to use `puppeteer.launch()` in order to actually use the plugins I set up via `puppeteer.use()`?

If so, doesn't that mean that it's only supported if you're not using plugins, which is pretty much the point of `puppeteer-extra`?

**Comment by joelgriffith** [comment]
You shouldn't have to use `launch`, they do have a `connect` method: https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra/src/index.ts#L14. I know others have used it as well, so I'd try giving that shot and seeing if it works for your needs.

**Comment by kevin-lindsay-1** [comment]
Thanks, this appears to work! I think I initially determined that using `connect` on `puppeteer-extra` wouldn't work because I was getting an issue related to the plugin's `onBrowser` event not receiving anything, which after some digging I later determined was a bug.

**Comment by lonkle** [comment]
> puppeteer-extra does have a connect method, so you can use it on the client end (in your code). Functions and other APIs don’t currently support it just yet

@joelgriffith Do you plan on implementing this in the future though? The endpoints work perfectly for my use case, but I want to feel more future proof while still solely the `function` endpoint to run my scripts. So, puppeteer-extra and further puppeteer-extra-stealth are something I'd want to add to those endpoints even if it came to making a pull request and adding them myself (at least I'd try 😂). Or at least have an environment variable to optionally run them (extra and / or stealth).

But do you have any opposition to using puppeteer-extra or puppeteer-extra-stealth on the self-hosted /function endpoint in the future? I'm trying to get all green on this page: https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html *by default* (because actually I was able to beat each of those protections from within the functions endpoint **except** for the chrome object, still fail that which is why I think I need puppeteer-stealth).
